name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  done:
    name: done
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Configure git to use HTTPS instead of SSH
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-nextest

      - name: Run project checks
        run: cargo make done
